site_name: Bootcamp Docs
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.arithmatex
  - pymdownx.inlinehilite

nav:
  - Home: index.md
  - Flowcharts:
      - Login Flow: login.md
      - Registration Flow: register.md
  - Features: features.md
  - About: about.md
